name: TATE
favicon: null
layout_spectrum: 0.5095086481887847
typography_spectrum: 0.4851051736623049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.35186949116177857
  lightness: 0.3076596928294748
  saturation: 0.9849395093042403
  rhythmicContrast: 0.27006229013204575
purpose: []
